// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '__API_KEY__',
    appId: '__APP_ID__',
    messagingSenderId: '__MESSAGING_SENDER_ID__',
    projectId: '__PROJECT_ID__',
    authDomain: '__AUTH_DOMAIN__',
    storageBucket: '__STORAGE_BUCKET__',
    measurementId: '__MEASUREMENT_ID__',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '__API_KEY__',
    appId: '__APP_ID__',
    messagingSenderId: '__MESSAGING_SENDER_ID__',
    projectId: '__PROJECT_ID__',
    storageBucket: '__STORAGE_BUCKET__',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '__API_KEY__',
    appId: '__APP_ID__',
    messagingSenderId: '__MESSAGING_SENDER_ID__',
    projectId: '__PROJECT_ID__',
    storageBucket: '__STORAGE_BUCKET__',
    iosClientId: '__IOS_CLIENT_ID__',
    iosBundleId: '__IOS_BUNDLE_ID__',
  );
}
